### ISSUE TITLE
Automatically Selects "CloudPRO Mac" if you have that product

### ISSUE THREAD

**Issue by awjudd** [hef/cacctl#15]
https://github.com/hef/cacctl/blob/3a94c02b2e5c3130af90d32e41cc21c63b9720f3/internal/client/parsebuildpage.go#L25

Reading this line of code, it looks like the first element is selected, which in my case is "CloudPRO Mac", which has no resources available.

![image](https://user-images.githubusercontent.com/1910996/147887677-2b3c7f5f-ac16-44ba-9382-39a3454106a9.png)
![image](https://user-images.githubusercontent.com/1910996/147887657-b7cdd496-b51d-47ec-b8d6-a291cc1c313a.png)

Can this be adjusted to skim through the text and skip over anything that says "Mac" since this is primarily focused on Linux VMs?

**Comment by hef** [comment]
can you save that page, and attach it to this issue? I'll end up using it as a unit test.    I don't have access to any other cac services, so I couldn't repro this locally.

**Comment by hef** [comment]
I'm like 90% sure that page doesn't have sensitive information in the source code, but double check before posting it.

**Comment by awjudd** [comment]
I PM-ed you a link to it.  It doesn't provide any sensitive information.
